# Generated by Django 2.2.3 on 2019-08-21 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transferation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_room_id', models.IntegerField()),
                ('new_room_id', models.IntegerField()),
                ('start_date', models.DateField()),
                ('surchage', models.IntegerField(default=0)),
                ('nb_days', models.IntegerField(default=0, editable=False)),
                ('water_debt', models.IntegerField(default=0, editable=False)),
                ('electricity_debt', models.IntegerField(default=0, editable=False)),
                ('total_debt', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('customer_name', models.CharField(max_length=200)),
                ('customer_id', models.IntegerField(default=0)),
                ('customer_phone', models.IntegerField(default=0)),
                ('room_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('num_bike', models.IntegerField(default=1)),
                ('bike_id', models.IntegerField(default=0)),
                ('parking_card_id', models.IntegerField(default=0)),
                ('customer_deposit', models.IntegerField(default=0)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('image_profile', models.FileField(blank=True, null=True, upload_to='')),
                ('image_cmnd', models.FileField(blank=True, default=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('water_start_num', models.IntegerField(default=0, editable=False)),
                ('water_end_num', models.IntegerField(default=0)),
                ('electricity_start_num', models.IntegerField(default=0, editable=False)),
                ('electricity_end_num', models.IntegerField(default=0)),
                ('surchage', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
