# Generated by Django 2.2.3 on 2019-08-16 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('customer_name', models.CharField(max_length=200)),
                ('customer_id', models.IntegerField(default=0)),
                ('customer_phone', models.IntegerField(default=0)),
                ('room_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('num_bike', models.IntegerField(default=1)),
                ('bike_id', models.IntegerField(default=0)),
                ('parking_card_id', models.IntegerField(default=0)),
                ('customer_deposit', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('image_profile', models.FileField(blank=True, null=True, upload_to='')),
                ('image_cmnd', models.FileField(blank=True, default=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('water_start_num', models.IntegerField(default=0)),
                ('water_end_num', models.IntegerField(default=0)),
                ('electricity_start_num', models.IntegerField(default=0)),
                ('electricity_end_num', models.IntegerField(default=0)),
                ('surchage', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.User')),
            ],
        ),
    ]
