# Generated by Django 2.2.3 on 2019-08-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transferation',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
