# Generated by Django 2.2.3 on 2019-08-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190821_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
