# Generated by Django 2.2.3 on 2019-08-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190822_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferation',
            name='electricity_debt',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='transferation',
            name='nb_days',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='transferation',
            name='total_debt',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='transferation',
            name='water_debt',
            field=models.IntegerField(editable=False),
        ),
    ]
