# Generated by Django 2.2.3 on 2019-08-24 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190822_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.User'),
        ),
    ]
