# Generated by Django 2.2.3 on 2019-08-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190824_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='user',
            field=models.IntegerField(),
        ),
    ]
