# Generated by Django 2.2.3 on 2019-08-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190824_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='new_room',
            field=models.IntegerField(default=-1),
        ),
    ]
